print("Hola! este es el sistema de comisiones\ningrese el nombre del vendedor y la venta")
nombre)=input("Nombre:	")
venta1=float(input("venta1:))
venta2=float(input("venta2:))
venta3=float(input("venta3:))
comision=((venta1+venta2+venta3)*12.5)/100
tventa=(venta1+venta2+venta3)
tcomisiones=tventas+comision
print("\nVendedor\tVentas\tComision")
print(nombre + "\t\t" + str(venta1))
print(nombre + "\t\t" + str(venta2))
print(nombre + "\t\t" + str(venta3))
print("\t\t\t" + str(comision")
print("\nTotal ventas\t Total+comision")
print(str(tventas) + "\t\t" + str(tcomision))
input()